// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taggy.Infrastructure.Data;

#nullable disable

namespace Taggy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Taggy.Domain.Entities.EmissionCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FuelId")
                        .HasColumnType("uuid")
                        .HasColumnName("fuel_id");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid>("TimeScaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_scale_id");

                    b.Property<decimal>("TotalEmission")
                        .HasColumnType("numeric")
                        .HasColumnName("total_emission");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.HasIndex("TimeScaleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("emission_calculations", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.Export", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.HasKey("Id");

                    b.ToTable("exports", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.Fuel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Co2Factor")
                        .HasColumnType("numeric")
                        .HasColumnName("co2_factor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("EfficiencyFactor")
                        .HasColumnType("numeric")
                        .HasColumnName("efficiency_factor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("fuels", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.TimeScale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer")
                        .HasColumnName("multiplier");

                    b.HasKey("Id");

                    b.ToTable("time_scales", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.UserVehicle", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("UserId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("user_vehicles", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Co2Emission")
                        .HasColumnType("numeric")
                        .HasColumnName("co2_emission");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("numeric")
                        .HasColumnName("consumption");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("engine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.VehicleFuel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdjustedConsumption")
                        .HasColumnType("numeric")
                        .HasColumnName("adjusted_consumption");

                    b.Property<decimal>("AdjustedEmission")
                        .HasColumnType("numeric")
                        .HasColumnName("adjusted_emission");

                    b.Property<Guid>("FuelId")
                        .HasColumnType("uuid")
                        .HasColumnName("fuel_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.HasIndex("VehicleId");

                    b.ToTable("vehicle_fuels", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.WasteCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Lanes")
                        .HasColumnType("integer")
                        .HasColumnName("lanes");

                    b.Property<decimal>("NonPrintRate")
                        .HasColumnType("numeric")
                        .HasColumnName("non_print_rate");

                    b.Property<decimal>("TicketWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("ticket_weight");

                    b.Property<Guid>("TimeScaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_scale_id");

                    b.Property<string>("TollName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("toll_name");

                    b.Property<decimal>("TotalWasteKg")
                        .HasColumnType("numeric")
                        .HasColumnName("total_waste_kg");

                    b.Property<int>("VehiclesPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("vehicles_per_day");

                    b.HasKey("Id");

                    b.HasIndex("TimeScaleId");

                    b.ToTable("waste_calculations", (string)null);
                });

            modelBuilder.Entity("Taggy.Domain.Entities.EmissionCalculation", b =>
                {
                    b.HasOne("Taggy.Domain.Entities.Fuel", "Fuel")
                        .WithMany("EmissionCalculations")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taggy.Domain.Entities.TimeScale", "TimeScale")
                        .WithMany("EmissionCalculations")
                        .HasForeignKey("TimeScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taggy.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("EmissionCalculations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");

                    b.Navigation("TimeScale");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Taggy.Domain.Entities.UserVehicle", b =>
                {
                    b.HasOne("Taggy.Domain.Entities.User", "User")
                        .WithMany("UserVehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taggy.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("UserVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Taggy.Domain.Entities.VehicleFuel", b =>
                {
                    b.HasOne("Taggy.Domain.Entities.Fuel", "Fuel")
                        .WithMany("VehicleFuels")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taggy.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleFuels")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Taggy.Domain.Entities.WasteCalculation", b =>
                {
                    b.HasOne("Taggy.Domain.Entities.TimeScale", "TimeScale")
                        .WithMany("WasteCalculations")
                        .HasForeignKey("TimeScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeScale");
                });

            modelBuilder.Entity("Taggy.Domain.Entities.Fuel", b =>
                {
                    b.Navigation("EmissionCalculations");

                    b.Navigation("VehicleFuels");
                });

            modelBuilder.Entity("Taggy.Domain.Entities.TimeScale", b =>
                {
                    b.Navigation("EmissionCalculations");

                    b.Navigation("WasteCalculations");
                });

            modelBuilder.Entity("Taggy.Domain.Entities.User", b =>
                {
                    b.Navigation("UserVehicles");
                });

            modelBuilder.Entity("Taggy.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("EmissionCalculations");

                    b.Navigation("UserVehicles");

                    b.Navigation("VehicleFuels");
                });
#pragma warning restore 612, 618
        }
    }
}
